name: Update Version XML

on:
  push:
    tags:
      - 'v*'

jobs:
  update-xml:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update versions in XML files
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          
          # Actualizar manifest.xml
          sed -i "s|<version>.*</version>|<version>$VERSION</version>|" manifest.xml
          
          # Actualizar mod_formulario_cv.xml
          sed -i "s|<version>.*</version>|<version>$VERSION</version>|" mod_formulario_cv.xml
          
          # Actualizar update.xml
          sed -i "s|<version>.*</version>|<version>$VERSION</version>|" update.xml
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Añadir los tres archivos al commit
          git add manifest.xml mod_formulario_cv.xml update.xml
          
          git commit -m "Actualización automática de versión a $VERSION"
          
          # Empujar cambios a la rama main
          git push origin main
