name: Update Version XML

on:
  push:
    tags:
      - 'v*'

jobs:
  update-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # FUERZA el checkout en la rama main
          token: ${{ secrets.GITHUB_TOKEN }} # NECESARIO para permisos de escritura

      - name: Update version in XML
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          
          # Actualizar mod_formulario_cv.xml
          sed -i "s|<version>.*</version>|<version>$VERSION</version>|" manifest.xml
          
          # Actualizar update.xml también (si lo tienes)
          sed -i "s|<version>.*</version>|<version>$VERSION</version>|" update.xml
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add mod_formulario_cv.xml update.xml
          git commit -m "Actualización automática de versión a $VERSION"
          
          # Empujar cambios a la rama main
          git push origin main
